name: Upload Code Coverage
on: [pull_request]
  
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run Unit tests
        run: make coverage
        env:
          SYSL_PLANTUML: http://www.plantuml.com/plantuml

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt